spring:
  application:
    name: backend-users
  flyway:
    enabled: true
    locations: classpath:migrations
    schemas: users
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        retry.backoff.ms: 1000
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        enable.idempotence: true

org:
  neo4j:
    pool:
      max-size: 50
      connection-acquisition-timeout: 60s
      max-connection-lifetime: 1h
      idle-time-before-connection-test: 10s
    connection-timeout: 30s
    max-transaction-retry-time: 30s

kafka-properties:
  follow-topic-name: follows
  unfollow-topic-name: unfollows
  block-topic-name: blocks
  unblock-topic-name: unblocks
  dead-letter-topic-name: deadLetters

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
  endpoint:
    health:
      show-details: always

app:
  domain:
  caches:
    user:
      key-prefix: "user:"
      ttl: 10m
    friends:
      key-prefix: "friends:"
      ttl: 15m
    suggestions:
      key-prefix: "suggestions:"
      ttl: 30m

jwt:
  access-token-expiration: 900000      # 15 minutes
  refresh-token-expiration: 604800000  # 7 days
  reset-token-expiration: 900000       # 15 minutes
  # Move to aws secret
  secret: 6b9c307c16b406bdec1358afb27560d1a9330dc1bf537efdf3b1788febd3221d

aws:
  ses:
    sender-email:
